### ISSUE TITLE
Difference between FSBO and FSBO2

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [releaunifreiburg/HPO-B#1]
Hi, I noticed that in `results` there are two json files for `FSBO`: `FSBO` and `FSBO2`, where `FSBO2` seems to significantly outperform `FSBO`. I would like to ask that is there any difference between the algorithms that generated those two files?

**Comment by sebastianpinedaar** [comment]
FSBO is the version of the code from the paper. We refactor it and open the code, and the results after re-running are in FSBO2. The code is in this repo: https://github.com/releaunifreiburg/FSBO

Technically, the only difference is the code implementation, but the hyperparameters of FSBO are the same.
