### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by LGro** [releaunifreiburg/HPO-B#3]
Dear HPO-B maintainers, I'd like to encourage you to [add a license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) to this repository so that folks can use it with confidence :relaxed:

**Comment by sebastianpinedaar** [comment]
Thanks for pointing it out. As result, we added the CC-BY license. :smile:

**Comment by LGro** [comment]
Thanks @sebastianpinedaar. It seems worth noting that a creative commons (CC) license is, while common for text and other media, a bit of an odd choice for source code and discouraged by the creative commons organization themselves:

> We recommend against using Creative Commons licenses for software.

https://creativecommons.org/faq/#Can_I_use_a_Creative_Commons_license_for_software.3F

Common permissive licenses for source code are the Apache-2.0 and MIT licenses, with the less permissive and stronger copyleft licenses being e.g. the ones from the GPL family. Please note, though, I'm not a lawyer and this is not legal advice.

**Comment by sebastianpinedaar** [comment]
Thanks for the feedback! We changed it to MIT license!
