### ISSUE TITLE
Incompatible license

### ISSUE THREAD

**Issue by geoalgo** [releaunifreiburg/HPO-B#4]
Hi,

The code is released with an MIT license, but it is not compatible with GPL3 (critical diagram code) as far as I know:

https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l

**Comment by geoalgo** [comment]
GPL3 is contagious so using another permissive license such as Apache 2.0 would not change the issue. From what I understand, you could either change the license of the repo to GPL3, provide instruction to download the critical diagram code and not include it in your source, or use another piece of code.

If you are interested in the latter, we recently added critical diagrams in syne tune (in a branch for now https://github.com/geoalgo/syne-tune/pull/2 but will merge it to mainline at some point). Those are released under Apache license so if you use those you could keep a permissive license.

**Comment by sebastianpinedaar** [comment]
Thanks for pointing it out. We removed the file accordingly and users are free to use any external tool!
